---
- name: Sniff packets between hosts using host machine
  hosts: localhost
  connection: local
  tasks:
    - name: Get the directory of the playbook
      set_fact:
        playbook_dir: "{{ playbook_dir }}"

    - name: Start Wireshark to sniff packets between hosts for 1 minute
      shell: "sudo timeout 60 tshark -i any -f 'host 192.168.56.106 and host 192.168.56.107' -w packets.pcap"
      args:
        chdir: "{{ playbook_dir }}"
