---
- name: Start packet sniffing on nodes
  hosts: Nodes
  become: yes
  tasks:
    - name: Start packet sniffing using tshark
      command: "sudo tshark -i any -w {{ playbook_dir }}/node_packets_{{ inventory_hostname }}.pcap"
      async: 3600
      poll: 0

