---
- name: Sniff packets from nodes using host machine
  hosts: localhost
  connection: local
  tasks:
    - name: Get the directory of the playbook
      set_fact:
        playbook_dir: "{{ playbook_dir }}"
    
    - name: Start Wireshark to sniff packets from nodes
      command: "sudo tshark -i any -f 'host {{ item }}' -w node_{{ item }}_packets.pcap"
      args:
        chdir: "{{ playbook_dir }}"
      with_items: "{{ groups['Nodes'] }}"
